#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PrivateGallery.Android.Resource", IsApplication=true)]

namespace PrivateGallery.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::PrivateGallery.Android.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::PrivateGallery.Android.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::PrivateGallery.Android.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::PrivateGallery.Android.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::PrivateGallery.Android.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::PrivateGallery.Android.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Attribute.layoutManager = global::PrivateGallery.Android.Resource.Attribute.layoutManager;
			global::com.refractored.fab.Resource.Attribute.reverseLayout = global::PrivateGallery.Android.Resource.Attribute.reverseLayout;
			global::com.refractored.fab.Resource.Attribute.spanCount = global::PrivateGallery.Android.Resource.Attribute.spanCount;
			global::com.refractored.fab.Resource.Attribute.stackFromEnd = global::PrivateGallery.Android.Resource.Attribute.stackFromEnd;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::PrivateGallery.Android.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::PrivateGallery.Android.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::PrivateGallery.Android.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::PrivateGallery.Android.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::PrivateGallery.Android.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::PrivateGallery.Android.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::PrivateGallery.Android.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::PrivateGallery.Android.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::PrivateGallery.Android.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.item_touch_helper_previous_elevation = global::PrivateGallery.Android.Resource.Id.item_touch_helper_previous_elevation;
			global::com.refractored.fab.Resource.Id.mini = global::PrivateGallery.Android.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::PrivateGallery.Android.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::PrivateGallery.Android.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::PrivateGallery.Android.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::PrivateGallery.Android.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::PrivateGallery.Android.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::PrivateGallery.Android.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::PrivateGallery.Android.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::PrivateGallery.Android.Resource.Styleable.FloatingActionButton_fab_size;
			global::com.refractored.fab.Resource.Styleable.RecyclerView = global::PrivateGallery.Android.Resource.Styleable.RecyclerView;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_android_orientation = global::PrivateGallery.Android.Resource.Styleable.RecyclerView_android_orientation;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_layoutManager = global::PrivateGallery.Android.Resource.Styleable.RecyclerView_layoutManager;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_reverseLayout = global::PrivateGallery.Android.Resource.Styleable.RecyclerView_reverseLayout;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_spanCount = global::PrivateGallery.Android.Resource.Styleable.RecyclerView_spanCount;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_stackFromEnd = global::PrivateGallery.Android.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000c
			public const int fab_colorDisabled = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int fab_colorNormal = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fab_colorPressed = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fab_colorRipple = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fab_shadow = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fab_size = 2130771983;
			
			// aapt resource value: 0x7f010009
			public const int indicatorColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int indicatorName = 2130771976;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int maxHeight = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int maxWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int minHeight = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int minWidth = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int fab_material_blue_500 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int theme_devicedefault_background = 2131230721;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040007
			public const int fab_elevation_lollipop = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int fab_scroll_threshold = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int fab_shadow_size = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int fab_size_mini = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int fab_size_normal = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int facebook = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gallery = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int uploadfolder = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int uploadphoto = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int FabButtonGallery = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int FabButtonPicture = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int GalleryList = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int PictureList = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int applyGalleryButton = 2131034116;
			
			// aapt resource value: 0x7f05001e
			public const int deleteGallery = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int editGallery = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int emailField = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int firstNameField = 2131034132;
			
			// aapt resource value: 0x7f05001b
			public const int galleryCount = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int galleryDate = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int galleryHeader = 2131034137;
			
			// aapt resource value: 0x7f050012
			public const int imageReg = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int indicator = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050015
			public const int lastNameField = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int loginView = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int mini = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int newGalleryHeader = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int normal = 2131034114;
			
			// aapt resource value: 0x7f050017
			public const int passwordField = 2131034135;
			
			// aapt resource value: 0x7f050009
			public const int passwordView = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int pickImageReg = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int pickPicture = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int pickedPhoto = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int pictureDescription = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int registerButton = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int signIn = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int signUpButton = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int ucPicture = 2131034140;
			
			// aapt resource value: 0x7f050011
			public const int uploadPictureFull = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateGalleryFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ForgotPasswordScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GalleryScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoadingDialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LoginScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PhotoEditScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RegistrationScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int UCGalleryItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int UCPictureLayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int galleryMenu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int ApplicationName = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Hello = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AVLoadingIndicatorView = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AVLoadingIndicatorView_Large = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int AVLoadingIndicatorView_Small = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int NoActionBar = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Theme_Custom = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AVLoadingIndicatorView = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 5
			public const int AVLoadingIndicatorView_indicatorColor = 5;
			
			// aapt resource value: 4
			public const int AVLoadingIndicatorView_indicatorName = 4;
			
			// aapt resource value: 3
			public const int AVLoadingIndicatorView_maxHeight = 3;
			
			// aapt resource value: 1
			public const int AVLoadingIndicatorView_maxWidth = 1;
			
			// aapt resource value: 2
			public const int AVLoadingIndicatorView_minHeight = 2;
			
			// aapt resource value: 0
			public const int AVLoadingIndicatorView_minWidth = 0;
			
			public static int[] FloatingActionButton = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
